# Generated by Django 5.1 on 2024-08-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='расстояние')),
            ],
            options={
                'verbose_name': 'таблица',
                'verbose_name_plural': 'таблицы',
            },
        ),
    ]
