# Generated by Django 5.1 on 2024-08-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableentry',
            options={'ordering': ['-date'], 'verbose_name': 'таблица', 'verbose_name_plural': 'таблицы'},
        ),
    ]
